name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and run tests
        run: ./gradlew clean testDebugUnitTest

      - name: List coverage report directory
        run: ls -R automotive/build/reports/jacoco/testDebugUnitTest/html

      - name: Print coverage report file
        run: cat automotive/build/reports/jacoco/testDebugUnitTest/html/index.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: automotive/build/reports/jacoco/testDebugUnitTest/html
